export interface MacroNode {
  id: string;
  label: string;
  position: [number, number, number];
  isHome: boolean;
}

export interface WordCloudDatum {
  text: string;
  weight: number;
}

export const MACRO_NODES: MacroNode[] = [
  { id: "node-current", label: "text1", position: [0, 0, 0], isHome: true },
  { id: "node-2", label: "text2", position: [-8, 0, -6], isHome: false },
  { id: "node-3", label: "text3", position: [8, 0, 2], isHome: false },
  { id: "node-4", label: "text4", position: [-3, 0, 8], isHome: false },
];

export const DEFAULT_SELECTED_NODE_ID = "node-current";

export const NODE_WORD_CLOUDS: Record<string, WordCloudDatum[]> = {
  "node-current": [
    { text: "text中学", weight: 98 },
    { text: "text中学南门", weight: 94 },
    { text: "text中学北侧", weight: 90 },
    { text: "text中学天桥", weight: 87 },
    { text: "text广场", weight: 85 },
    { text: "text中心广场", weight: 83 },
    { text: "text广场东口", weight: 81 },
    { text: "text主干道", weight: 76 },
    { text: "text主干道南段", weight: 74 },
    { text: "text主干道北段", weight: 72 },
    { text: "text社区", weight: 68 },
    { text: "text核心社区", weight: 66 },
    { text: "text沿街社区", weight: 64 },
    { text: "text园区", weight: 63 },
    { text: "text科技园区", weight: 61 },
    { text: "text创意园区", weight: 59 },
    { text: "text地铁口", weight: 58 },
    { text: "text地铁A口", weight: 56 },
    { text: "text地铁B口", weight: 55 },
    { text: "text商圈", weight: 54 },
    { text: "text夜间商圈", weight: 53 },
    { text: "text车站", weight: 50 },
    { text: "text公交枢纽", weight: 49 },
    { text: "text步行街", weight: 46 },
    { text: "text步行街中段", weight: 45 },
    { text: "text医院", weight: 42 },
    { text: "text医院急诊", weight: 41 },
    { text: "text文创园", weight: 38 },
    { text: "text文创园北区", weight: 37 },
    { text: "text写字楼", weight: 33 },
    { text: "text写字楼集群", weight: 32 },
    { text: "text停车换乘点", weight: 30 },
    { text: "text商业连廊", weight: 29 },
    { text: "text河岸步道", weight: 27 },
    { text: "text社区驿站", weight: 25 },
    { text: "text便民中心", weight: 23 },
  ],
  "node-2": [
    { text: "text实验小学", weight: 95 },
    { text: "text实验小学西门", weight: 92 },
    { text: "text实验小学周边", weight: 89 },
    { text: "text物流枢纽", weight: 84 },
    { text: "text物流枢纽西区", weight: 82 },
    { text: "text物流枢纽南区", weight: 79 },
    { text: "text老城区", weight: 72 },
    { text: "text老城区主街", weight: 70 },
    { text: "text老城区巷口", weight: 69 },
    { text: "text河道口", weight: 68 },
    { text: "text河道口桥头", weight: 66 },
    { text: "text夜市", weight: 63 },
    { text: "text夜市北排", weight: 61 },
    { text: "text客运站", weight: 59 },
    { text: "text客运站西广场", weight: 58 },
    { text: "text综合体", weight: 55 },
    { text: "text综合体停车场", weight: 54 },
    { text: "text社区医院", weight: 51 },
    { text: "text社区医院门诊", weight: 50 },
    { text: "text文旅区", weight: 47 },
    { text: "text文旅区东段", weight: 46 },
    { text: "text停车场", weight: 43 },
    { text: "text停车场南侧", weight: 41 },
    { text: "text巷道", weight: 39 },
    { text: "text巷道交汇点", weight: 37 },
    { text: "text餐饮街", weight: 34 },
    { text: "text餐饮街入口", weight: 33 },
    { text: "text旧改片区", weight: 31 },
    { text: "text水岸廊桥", weight: 29 },
    { text: "text仓配中心", weight: 27 },
    { text: "text快递集散点", weight: 25 },
    { text: "text便民停车带", weight: 23 },
  ],
  "node-3": [
    { text: "text学院路", weight: 96 },
    { text: "text学院路南段", weight: 93 },
    { text: "text学院路北段", weight: 90 },
    { text: "text产业园", weight: 83 },
    { text: "text产业园一期", weight: 81 },
    { text: "text产业园二期", weight: 79 },
    { text: "text高新园", weight: 79 },
    { text: "text高新园核心区", weight: 77 },
    { text: "text商业街", weight: 71 },
    { text: "text商业街东侧", weight: 69 },
    { text: "text仓储区", weight: 66 },
    { text: "text仓储区北仓", weight: 64 },
    { text: "text居住区", weight: 61 },
    { text: "text居住区中庭", weight: 60 },
    { text: "text公交总站", weight: 57 },
    { text: "text公交总站出入口", weight: 56 },
    { text: "text科研楼", weight: 53 },
    { text: "text科研楼群", weight: 51 },
    { text: "text文体中心", weight: 48 },
    { text: "text文体中心南馆", weight: 47 },
    { text: "text主路口", weight: 44 },
    { text: "text主路口东北角", weight: 43 },
    { text: "text地铁换乘", weight: 40 },
    { text: "text地铁换乘大厅", weight: 39 },
    { text: "text文化广场", weight: 35 },
    { text: "text文化广场南区", weight: 34 },
    { text: "text创新孵化楼", weight: 32 },
    { text: "text人才公寓", weight: 30 },
    { text: "text会客中心", weight: 28 },
    { text: "text园区绿轴", weight: 26 },
    { text: "text停车换电点", weight: 24 },
  ],
  "node-4": [
    { text: "text高中", weight: 94 },
    { text: "text高中南门", weight: 91 },
    { text: "text高中北区", weight: 88 },
    { text: "text滨江带", weight: 82 },
    { text: "text滨江带东段", weight: 80 },
    { text: "text滨江带西段", weight: 78 },
    { text: "text会展中心", weight: 75 },
    { text: "text会展中心北馆", weight: 73 },
    { text: "text休闲区", weight: 69 },
    { text: "text休闲区步道", weight: 67 },
    { text: "text办公区", weight: 64 },
    { text: "text办公区A座", weight: 62 },
    { text: "text社区中心", weight: 60 },
    { text: "text社区中心东翼", weight: 58 },
    { text: "text交通口", weight: 56 },
    { text: "text交通口匝道", weight: 55 },
    { text: "text商贸区", weight: 52 },
    { text: "text商贸区中环", weight: 51 },
    { text: "text市场", weight: 47 },
    { text: "text市场南门", weight: 46 },
    { text: "text公园", weight: 43 },
    { text: "text公园湖区", weight: 42 },
    { text: "text道路节点", weight: 39 },
    { text: "text道路节点西口", weight: 38 },
    { text: "text综合站", weight: 34 },
    { text: "text综合站换乘层", weight: 33 },
    { text: "text滨水广场", weight: 31 },
    { text: "text会展停车场", weight: 29 },
    { text: "text共享办公区", weight: 27 },
    { text: "text文化廊道", weight: 25 },
    { text: "text夜间步道", weight: 23 },
  ],
};
